// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_API from "./routes/api/API.tsx";
import * as $id_id_ from "./routes/id/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $proyecto from "./routes/proyecto.tsx";
import * as $ListaPeliculas from "./islands/ListaPeliculas.tsx";
import * as $MostrarProyectos from "./islands/MostrarProyectos.tsx";
import * as $Proyectos from "./islands/Proyectos.tsx";
import * as $UnaPelicula from "./islands/UnaPelicula.tsx";
import * as $Volver from "./islands/Volver.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/API.tsx": $api_API,
    "./routes/id/[id].tsx": $id_id_,
    "./routes/index.tsx": $index,
    "./routes/proyecto.tsx": $proyecto,
  },
  islands: {
    "./islands/ListaPeliculas.tsx": $ListaPeliculas,
    "./islands/MostrarProyectos.tsx": $MostrarProyectos,
    "./islands/Proyectos.tsx": $Proyectos,
    "./islands/UnaPelicula.tsx": $UnaPelicula,
    "./islands/Volver.tsx": $Volver,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
